#!/usr/bin/env python

"""k(kubectl)++ ... only better
Usage:
kk get (podnode|pn) [options]

Options:
    -h --help    show this
    -l STRING    label selector
    -f STRING    field selector
    -e STRING    exclude
    -o output    pydash format plus padding info, ie. node.metadata.name:62
    -w           watch mode
"""

"""
pyb publish
pip install .tar.gz
runMyScript.py
uninstall
"""

import logging
import sys
import logging
from docopt import docopt
arguments = docopt(__doc__, version='${version}', help=True)

#src/main/scripts/kk get pn \
#                       -l 'app=streamtech-ibms-service/streamtech-cdn-selection-service' \
#                       -f 'metadata.namespace=streamtech/content/commerce' \
#                       -e 'metadata.owner_references[0].kind=DaemonSet'
#                       -o 'pod_name:62,node.metadata.labels.lifecycle,namespace,node.metadata.name:62'
#                       -w 

print(arguments)